name: SmallerKiln_JH
piecehammer: Hammer
m_name: Small Kiln
sizeMultiplier: 0.5
m_description: A tiny version of the Charcoal Kiln
customIcon: 
clonePrefabName: charcoal_kiln
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: TinyVersions
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: true
wearNTearData:
  health: 1500
  damageModifiers:
    m_blunt: Resistant
    m_slash: Resistant
    m_pierce: Resistant
    m_chop: Resistant
    m_pickaxe: Normal
    m_fire: Immune
    m_frost: Immune
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData:
  addOreTooltip: $piece_smelter_add $item_wood
  emptyOreTooltip: $piece_smelter_empty
  fuelItem: 
  maxOre: 50
  maxFuel: 
  fuelPerProduct: 
  secPerProduct: 15
  spawnStack: 
  requiresRoof: 
  addOreAnimationLength: 
  smelterConversion:
  - FromName: Wood
    ToName: Coal
    Remove: false
  - FromName: FineWood
    ToName: Coal
    Remove: false
  - FromName: RoundLog
    ToName: Coal
    Remove: false
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
build:
- Stone:20:1:True
- SurtlingCore:5:1:True
