name: GB_Oven
piecehammer: _GBCastleKit
m_name: $GB_Oven
sizeMultiplier: 1
m_description: $GB_Oven_Description
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_artisanstation
piecehammerCategory: Furniture
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 500
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Resistant
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData:
  addItemTooltip: $piece_oven_additem
  overcookedItem: Coal
  fuelItem: 
  requireFire: false
  maxFuel: 
  secPerFuel: 
  cookConversion:
  - FromName: BreadDough
    ToName: Bread
    CookTime: 50
    Remove: false
  - FromName: FishAndBreadUncooked
    ToName: FishAndBread
    CookTime: 50
    Remove: false
  - FromName: HoneyGlazedChickenUncooked
    ToName: HoneyGlazedChicken
    CookTime: 50
    Remove: false
  - FromName: LoxPieUncooked
    ToName: LoxPie
    CookTime: 50
    Remove: false
  - FromName: MagicallyStuffedShroomUncooked
    ToName: MagicallyStuffedShroom
    CookTime: 50
    Remove: false
  - FromName: MeatPlatterUncooked
    ToName: MeatPlatter
    CookTime: 50
    Remove: false
  - FromName: MisthareSupremeUncooked
    ToName: MisthareSupreme
    CookTime: 50
    Remove: false
  - FromName: RoastedCrustPieUncooked
    ToName: RoastedCrustPie
    CookTime: 50
    Remove: false
  - FromName: PiquantPieUncooked
    ToName: PiquantPie
    CookTime: 50
    Remove: false
  - FromName: UncookedBerryCakePlains_TW
    ToName: BerryCakePlains_TW
    CookTime: 50
    Remove: false
  - FromName: FishPieUncooked_TW
    ToName: FishPie_TW
    CookTime: 50
    Remove: false
  - FromName: ShroomTartUncooked_TW
    ToName: ShroomTart_TW
    CookTime: 50
    Remove: false
  - FromName: MeatPieUncooked_TW
    ToName: MeatPie_TW
    CookTime: 50
    Remove: false
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
build:
- Iron:6:1:True
- Stone:12:1:True
- SurtlingCore:4:1:True
