name: kg_EnchantScroll_Armor_Blessed_S
clonePrefabName: 
craftingStation: Scroll Station
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Eitr:5:0:True
- JuteBlack_TW:5:0:True
- InfusedCrystal_JH:10:0:True
- kg_EnchantScroll_Armor_S:1:0:True
